sudo: false

git:
  depth: false

language: python

python:
  - 2.7

install:
  - pip install .

script:
# tests need to run independently as there is conflict with luigi's local scheduler
  - python -m unittest tests.test_monitor.TestLuigiMonitor.test_monitor_no_message
  - python -m unittest tests.test_monitor.TestLuigiMonitor.test_monitor_missing_message
  - python -m unittest tests.test_monitor.TestLuigiMonitor.test_monitor_success_message
  - python setup.py bdist_wheel
